
"""
Each new term in the fibonacci sequence is generated by adding the previous two terms.

Given a limit, find the sum of all the even numbers in the fibonacci sequence up until the limit

"""
# O(n)
def Solution(limit: int) -> int:

    x = 0
    total = 2  # Set the sum to the initial even starting term in the sequence
    previous_two_terms = [1,2]  # Create a stack to manage the two numbers being considered

    # While the limit has yet to be reached
    while x < limit:

        # Find the next term in sequence
        x = previous_two_terms[0] + previous_two_terms[1]

        # if even, sum it
        if x % 2 == 0:
            total += x

        # Remove the lower of the towo values
        previous_two_terms.pop(0)
        # Add the new term
        previous_two_terms.append(x)

    return total




if __name__ == '__main__':
    
    solution = Solution(4000000)
    print(solution)
